apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 9.1.8
      helm:
        valueFiles:
          - $values/argocd/values.yaml
    - repoURL: https://github.com/byulmaru/infrastructure.git
      targetRevision: HEAD
      ref: values
      path: argocd

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - CreateNamespace=true
