apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://kubernetes-sigs.github.io/descheduler/
      chart: descheduler
      targetRevision: 0.34.0
      valueFiles:
        - $values/descheduler/values.yaml
    - repoURL: https://github.com/byulmaru/infrastructure.git
      targetRevision: HEAD
      path: descheduler
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - CreateNamespace=true
