apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-operator
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://helm.elastic.co
    chart: eck-operator
    targetRevision: 3.2.0
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-system
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - CreateNamespace=true
