apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts
      chart: infisical-standalone
      targetRevision: 1.7.2
      helm:
        valueFiles:
          - $values/infisical/values.yaml
    - repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts
      chart: secrets-operator
      targetRevision: 0.10.16
      helm:
        valueFiles:
          - $values/infisical/values-operator.yaml
    - repoURL: https://github.com/byulmaru/infrastructure.git
      targetRevision: HEAD
      ref: values
      path: infisical

  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /metadata/annotations/updatedAt
        - /spec/template/metadata/annotations/updatedAt
