apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/byulmaru/infrastructure.git
    - https://argoproj.github.io/argo-helm
    - https://kubernetes-sigs.github.io/metrics-server/
    - https://cloudnative-pg.github.io/charts
    - https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts
    - https://pkgs.tailscale.com/helmcharts
    - https://kubernetes.github.io/ingress-nginx
    - oci://quay.io/jetstack/charts/cert-manager
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
