apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://pkgs.tailscale.com/helmcharts
      chart: tailscale-operator
      targetRevision: 1.90.9
      helm:
        valueFiles:
          - $values/tailscale/values.yaml
    - repoURL: https://github.com/byulmaru/infrastructure.git
      targetRevision: HEAD
      ref: values
      path: tailscale

  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - CreateNamespace=true
