apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: postgres
spec:
  resyncInterval: 60
  authentication:
    kubernetesAuth:
      identityId: 953a7c79-6486-44d6-a6be-04dd7eda1853
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: secret
        namespace: infisical

      secretsScope:
        projectId: 14e34fd2-419e-4762-bb88-97561501e19b
        envSlug: prod
        secretsPath: /postgres
  managedKubeSecretReferences:
    - secretName: postgres
      secretNamespace: sentry
      secretType: kubernetes.io/basic-auth
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: secrets
spec:
  resyncInterval: 60
  authentication:
    kubernetesAuth:
      identityId: 953a7c79-6486-44d6-a6be-04dd7eda1853
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: secret
        namespace: infisical

      secretsScope:
        projectId: 14e34fd2-419e-4762-bb88-97561501e19b
        envSlug: prod
        secretsPath: /
  managedKubeSecretReferences:
    - secretName: secrets
      secretNamespace: sentry
      secretType: Opaque
