apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: api-server
spec:
  type: kube-apiserver
  replicas: 2
  tags: ["tag:k8s"]
  proxyClass: kube-apiserver
  kubeAPIServer:
    mode: auth
