apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 1

  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover

  postgresql:
    pg_hba:
      - host all all all scram-sha-256

  bootstrap:
    initdb:
      database: outline
      owner: outline
      secret:
        name: postgres

  storage:
    size: 10Gi
    storageClass: oci-bv-low

  managed:
    roles:
      - name: outline
        ensure: present
        login: true
        inRoles:
          - pg_monitor

  resources:
    limits:
      memory: "512Mi"
      cpu: "125m"
