apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: postgres
spec:
  resyncInterval: 60
  authentication:
    kubernetesAuth:
      identityId: 953a7c79-6486-44d6-a6be-04dd7eda1853
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: secret
        namespace: infisical

      secretsScope:
        projectId: 6ed7da22-ba91-4999-9b84-64c8e8bf7e3a
        envSlug: prod
        secretsPath: /postgres
  managedKubeSecretReferences:
    - secretName: postgres
      secretNamespace: outline
      secretType: kubernetes.io/basic-auth
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: outline
spec:
  resyncInterval: 60
  authentication:
    kubernetesAuth:
      identityId: 953a7c79-6486-44d6-a6be-04dd7eda1853
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: secret
        namespace: infisical

      secretsScope:
        projectId: 6ed7da22-ba91-4999-9b84-64c8e8bf7e3a
        envSlug: prod
        secretsPath: /
  managedKubeSecretReferences:
    - secretName: outline
      secretNamespace: outline
      secretType: Opaque
