apiVersion: batch/v1
kind: Job
metadata:
  name: clickhouse-init
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init
          image: docker.io/clickhouse/clickhouse-server:25.10.2.65
          command:
            - sh
            - -c
            - |
              until clickhouse-client --host main-clickhouse-headless --query "SELECT 1"; do
                echo "Waiting for ClickHouse..."
                sleep 5
              done
              clickhouse-client --host main-clickhouse-headless --query "CREATE DATABASE IF NOT EXISTS openpanel"
  backoffLimit: 12
