apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: postgres
spec:
  resyncInterval: 60
  authentication:
    kubernetesAuth:
      identityId: 953a7c79-6486-44d6-a6be-04dd7eda1853
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: secret
        namespace: infisical

      secretsScope:
        projectId: 1dc38b45-6a97-42d9-8b4f-dd79b03a50af
        envSlug: prod
        secretsPath: /postgres
  managedKubeSecretReferences:
    - secretName: postgres
      secretNamespace: openpanel
      secretType: kubernetes.io/basic-auth
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: app
spec:
  resyncInterval: 60
  authentication:
    kubernetesAuth:
      identityId: 953a7c79-6486-44d6-a6be-04dd7eda1853
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: secret
        namespace: infisical

      secretsScope:
        projectId: 1dc38b45-6a97-42d9-8b4f-dd79b03a50af
        envSlug: prod
        secretsPath: /
  managedKubeSecretReferences:
    - secretName: secrets
      secretNamespace: openpanel
      secretType: Opaque
