apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: secret
  namespace: cert-manager
spec:
  resyncInterval: 60
  authentication:
    kubernetesAuth:
      identityId: 953a7c79-6486-44d6-a6be-04dd7eda1853
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: secret
        namespace: infisical

      secretsScope:
        projectId: d69374fd-25c7-4083-b9f3-535a60586823
        envSlug: prod
        secretsPath: /cert-manager
  managedKubeSecretReferences:
    - secretName: secret
      secretNamespace: cert-manager
